version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - FLASK_RUN_HOST=0.0.0.0
      - PORT=8050
    restart: always